# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cgpt < Formula
  desc "A simple command line tool for working with LLMs."
  homepage "https://github.com/tmc/cgpt"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmc/cgpt/releases/download/v0.1.1/cgpt_Darwin_x86_64.tar.gz"
      sha256 "6cc5989d77a8e5bc31d42731351e36f496eef0239b98fb72c6b433b345da0502"

      def install
        bin.install "cgpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmc/cgpt/releases/download/v0.1.1/cgpt_Darwin_arm64.tar.gz"
      sha256 "6849a1a72f868508fc742b8bd2a71627f0de53645d69389f84194046ae38a1cd"

      def install
        bin.install "cgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tmc/cgpt/releases/download/v0.1.1/cgpt_Linux_x86_64.tar.gz"
      sha256 "b2f110040ff2d30900237c40daf6712fd206176d57a4481b790d5aab63456178"

      def install
        bin.install "cgpt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmc/cgpt/releases/download/v0.1.1/cgpt_Linux_arm64.tar.gz"
      sha256 "299770b5c1b6b372d7198bd22bb960067a7a0b022260a3bd54c72a062e6849db"

      def install
        bin.install "cgpt"
      end
    end
  end
end
