# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cgpt < Formula
  desc "A simple command line tool for working with LLMs."
  homepage "https://github.com/tmc/cgpt"
  version "0.2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/tmc/cgpt/releases/download/v0.2.0/cgpt_Darwin_x86_64.tar.gz"
      sha256 "ef9405af73339d847da838d9dce73ccca5aea6a3cec73b52ec816a9a4e13033e"

      def install
        bin.install "cgpt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/tmc/cgpt/releases/download/v0.2.0/cgpt_Darwin_arm64.tar.gz"
      sha256 "2f8d789cc234696ae180f4c4578a596212ec73ad88e5cf877e836bceb7bba822"

      def install
        bin.install "cgpt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/tmc/cgpt/releases/download/v0.2.0/cgpt_Linux_x86_64.tar.gz"
      sha256 "b40117c0cb78cfe8eeba8d86974dfa0dc8af8d8b0cf2a0ff47f4fe4e929928ae"

      def install
        bin.install "cgpt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/tmc/cgpt/releases/download/v0.2.0/cgpt_Linux_arm64.tar.gz"
      sha256 "1a9f1f05c8c60b4b899638e4932f1adb931ba3e8abe1c768e95cd2ca040c33ca"

      def install
        bin.install "cgpt"
      end
    end
  end
end
