#!/bin/bash
set -euo pipefail
(./ctx-src; ctx-exec cat .hist; ctx-exec git st .)| cgpt -s 'output antthinking layers before you being your task' -p "# this bash script will adjust goals, but first think:" |tee next-step.sh

